### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by devinsba** [openzipkin/zipkin-aws#117]
With the SDK instrumentation finished I think this is a good time to summarize what we feel should be included or addressed before we release a version 1.0 of this library.

## Existing issues

- [ ] #60 Add an XRay `ErrorHandler` impl, and associated storage code
- [ ] #73 Add better hooks to XRay storage to allow RPC instrumentation to map nicely
- [ ] #108 XRay configured sampler
- [ ] #116 Intermediate error handling on V2 SDK Instrumentation

## Possible missing features

The following are features I can come up with by reading through the service list

- `FinishedSpanHandler` for tagging spans with host/container metadata
- `TraceContext.Extractor`s for Lambda (there are multiple ways this can be injected to a lambda)
- Service specific tags in SDK instrumentation for Dynamo and SQS (for XRay support)
- #45 DynamoDB storage support, this needs a champion and I don't think we hit rule of 3 on it either
- SNS, SQS, and Kinesis propagation handlers ([smarthings](https://github.com/SmartThingsOSS/smartthings-brave) have built the first 2
- Kinesis Streaming Dependencies job (we attic-ed the first one)
- MQTT propagation that supports AWS IoT
- A tool for extracting XRay data to add into Zipkin (API Gateway, Lambda)

**Comment by devinsba** [comment]
Anyone have any thoughts on when we should feel comfortable calling this stable?

cc @llinder @adriancole @cemo @openzipkin/core

**Comment by adriancole** [comment]
I think it is stable if the entry points to the SDK tracing and xray
reporting are stable.
